@url = http://localhost:5556

### GET JOBS 
GET {{url}}/jobs

### ADD JOBS POST 
POST {{url}}/jobs 
content-type:application/json 

{
    "jobTitle": "Vue Developer",
    "description": "Requires vue.js skills!"
}